### ISSUE TITLE
Fails on very large NS RRsets

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster#1139]
Zonemaster fails on `corp.ds.fedex.com` (an incredible number of NS records) with "BACKEND_TEST_AGENT:    Zonemaster was unable to start or finish the test. "

https://zonemaster.fr/en/result/c52681a3e892fca7

**Comment by pnax** [comment]
> an incredible number of NS records

88 records is indeed an incredible number of NS records ^^'.

Our current Backend implementation stops a test after [`max_zonemaster_execution_time`](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/Configuration.md#max_zonemaster_execution_time) seconds to avoid waiting for too long. Since we run all tests and requests sequentially, such zone can't be currently tested using zonemaster.fr (or zonemaster.net) because of the configured value `max_zonemaster_execution_time`. A workaround could be to try with the [Zonemaster-CLI](https://github.com/zonemaster/zonemaster-cli/) component (grab a cup of coffee/tea/whatever while running this test).

Thinking about this issue, and how Zonemaster could be improved:
* run queries concurrently (we have a current discussion to improve Zonemaster performances by v2023.2)
* keep track of all tests performed before reaching `max_zonemaster_execution_time` and display their results and the CRITICAL message " Zonemaster was unable to start or finish the test."

**Comment by bortzmeyer** [comment]
At the very least, the error message should be better. Something like "execution took too long (the current limit is XXX seconds), may be too many name servers or not responsive enough."'

**Comment by pnax** [comment]
Good point. I've opened https://github.com/zonemaster/zonemaster-backend/pull/1082 to meet this.

**Comment by matsduf** [comment]
With https://github.com/zonemaster/zonemaster-backend/pull/1082 Zonemaster will still break when the NS RRset is extremely large (and has unreachable members) but at least the message gives clearer information. Use zonemaster-cli to test such domain names. Or install your own backend and increase the timeout. We close this issue for now.
