### ISSUE TITLE
Test for EDNS features

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster#640]
Only version 0 of EDNS has been defined. If the query has set a higher version then BADVERS is expected. Zonemaster should test for that.

There could be other EDNS compliance tests to do. See https://dnsflagday.net/

**Comment by jtalir** [comment]
I think that right now is quite good opportunity to integrate this checks into Zonemaster. There is an ongoing pressure for domain operators to check their domains because of dnsflagday and it would be better to point them to Zonemaster that also checks other issues rather than to specific checker dedicated only to EDNS issues.

**Comment by sandoche2k** [comment]
ZM Wrongly tests EDNS https://zonemaster.net/result/d1645a013e813d12. I will add an issue

**Comment by matsduf** [comment]
@jelu, thank you for poiting it out. We have that on our agenda for our next face-to-face meeting next week.

**Comment by sandoche2k** [comment]
@matsduf could be closed?
