### ISSUE TITLE
consistency05: Empty error

### ISSUE THREAD

**Issue by cgsecurity** [zonemaster/zonemaster#840]
While checking the domain cgsecurity.org, https://zonemaster.net/result/38581361721ccd55 returns an empty error message for consistency05. An explicit error message should be displayed.
Note that the DNS servers are IPv4 only.

**Comment by matsduf** [comment]
Thank you, for pointing it out. It has been fixed in the develop branch, which will be the upcoming release that we think will come by end of April 2020.

The error is also -- an error -- which has been fixed in the develop branch. When I run the test with `zonemaster-cli` (same version) I get the following incorrect error:

```
   6.77 ERROR     CONSISTENCY:OUT_OF_BAILIWICK_ADDR_MISMATCH parent_addresses=dns03003.global-asp.net./193.168.50.250; zone_addresses=DNS03003.global-asp.net./193.168.50.250
```

When I test with code from develop branch, the false error is not there.

@cgsecurity, than you again for reporting and unless you have more questions in this issue I will close this.
